# SERVER
server.port=8090

# APP NAME
spring.application.name=GATEWAY

# SPRING CLOUD CONFIG
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# GATEWAY CORS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# LOGGING
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

# EUREKA
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA:http://localhost:8761/eureka}
eureka.client.healthcheck.enabled=true